<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Last tickets' => 'Последние тикеты',
    'New Tickets Today' => 'Новые тикеты на сегодня',
    'Tickets closed: oun' => '',
    'Unanswered tickets' => 'Неотвеченные тикеты',
    'STATUS_ACTIVE' => '@@СТАТУС АКТИВ@@',
    'STATUS_DELETED' => '@@СТАТУС УДАЛЕНО@@',
    'STATUS_INACTIVE' => '@@СТАТУС НЕАКТИВ@@',
    'You\'ve received a ticket' => '@@Вы получили тикет@@',
    'Active' => 'Активный',
    'Add Category' => 'Добавить категорию',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить?',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Category: {NAME}' => 'Категория: {NAME}',
    'Close' => 'Закрыть',
    'Closed' => 'Закрыто',
    'Content' => 'Контент',
    'Create' => 'Создать',
    'Created At' => 'Создано',
    'Created By' => 'Создано',
    'Delete' => 'Удалить',
    'Email' => 'Email',
    'Greetings from {APP},' => 'Приветствие из {APP},',
    'Hello Admin,' => 'Привет Админ',
    'ID' => 'ID',
    'Id Ticket' => 'Id Ticket\'',
    'Inactive' => 'Неактивный',
    'My Tickets' => 'Мои тикеты',
    'Open' => 'Открыто',
    'Open Ticket' => 'Открыть тикет',
    'Reply' => 'Ответить',
    'Reset' => 'Сброс',
    'Search' => 'Поиск',
    'Site' => 'Сайт',
    'Status' => 'Статус',
    'Status: {STATUS}' => 'Статус: {STATUS}',
    'Subject: {TITLE}' => 'Тема: {TITLE}',
    'Telegram' => 'Telegram',
    'Ticket #{ID}' => 'Тикет #{ID}',
    'Ticket #{ID}: New reply from {NAME}:' => 'Тикет #{ID}: Новый ответ от {NAME}:',
    'Ticket System' => 'Система тикетов',
    'Ticket was closed automatically due to inactivity.' => 'Тикет был закрыт автоматически из-за неактивности',
    'Tickets' => 'Тикеты',
    'Title' => 'Название',
    'Unknown' => 'Неизвестно',
    'Update' => 'Обновить',
    'Update: {NAME}' => 'Обновить: {NAME}',
    'Updated At' => 'Обновлено',
    'View Ticket' => 'Просмотреть тикет',
    'View Ticket: {URL}' => 'Просмотреть тикет: {URL}',
    'Waiting' => 'Ожидание',
    'You\'ve received a ticket (#{ID}) from {APP}' => 'Вы получили тикет (#{ID}) от {APP}',
    '[{APP} Ticket #{ID}] Re: {TITLE}' => '[{APP} Ticket #{ID}] Re: {TITLE}',
    '{APP}: Ticket #{ID} updated' => '{APP}: Ticket #{ID} обновился',
    '{USER} ({EMAIL}) have opened a ticket with the following message:' => '{USER} ({EMAIL}) открыл тикет с таким сообщением:',
    '{USER} closed the ticket.' => '{USER} закрыл тикет.',
];
