<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Last tickets' => 'Letzte Tickets',
    'New Tickets Today' => 'Neue Tickets heute',
    'Tickets closed: oun' => '',
    'Unanswered tickets' => 'Unbeantworte Tickets',
    'STATUS_ACTIVE' => '',
    'STATUS_DELETED' => '',
    'STATUS_INACTIVE' => '',
    'You\'ve received a ticket' => '',
    'Active' => 'Aktiv',
    'Add Category' => 'Kategorie hinzufügen',
    'Are you sure you want to delete this item?' => 'Wollen Sie wirklich das Element löschen?',
    'Categories' => 'Kategorien',
    'Category' => 'Kategorie',
    'Category: {NAME}' => 'Kategorie: {NAME}',
    'Close' => 'Schließen',
    'Closed' => 'Geschlossen',
    'Content' => 'Inhalt',
    'Create' => 'Erstellen',
    'Created At' => 'Erstellt am',
    'Created By' => 'Erstellt durch',
    'Delete' => 'Löschen',
    'Email' => 'E-Mail',
    'Greetings from {APP},' => 'Grüße von {APP},',
    'Hello Admin,' => 'Hallo Admin,',
    'ID' => 'ID',
    'Id Ticket' => 'Id Ticket\'',
    'Inactive' => 'Inaktiv',
    'My Tickets' => 'Meine Tickets',
    'Open' => 'Offen',
    'Open Ticket' => 'Ticket erstellen',
    'Reply' => 'Antworten',
    'Reset' => 'Reset',
    'Search' => 'Suche',
    'Site' => 'Seite',
    'Status' => 'Status',
    'Status: {STATUS}' => 'Status: {STATUS}',
    'Subject: {TITLE}' => 'Betreff: {TITLE}',
    'Telegram' => 'Telegram',
    'Ticket #{ID}' => 'Ticket #{ID}',
    'Ticket #{ID}: New reply from {NAME}:' => 'Ticket #{ID}: Neue Antwort von {NAME}:',
    'Ticket System' => 'Ticket System',
    'Ticket was closed automatically due to inactivity.' => 'Ticket wurde automatisch geschlossen wegen inaktivität.',
    'Tickets' => 'Tickets',
    'Title' => 'Titel',
    'Unknown' => 'Unbekannt',
    'Update' => 'Aktualisierung',
    'Update: {NAME}' => 'Aktualisierung: {NAME}',
    'Updated At' => 'Aktualisiert am',
    'View Ticket' => 'Ticket anzeigen',
    'View Ticket: {URL}' => 'Ticket anzeigen: {URL}',
    'Waiting' => 'Warten',
    'You\'ve received a ticket (#{ID}) from {APP}' => 'Du hast ein Ticket (#{ID}) empfangen von {APP}',
    '[{APP} Ticket #{ID}] Re: {TITLE}' => '[{APP} Ticket #{ID}] Re: {TITLE}',
    '{APP}: Ticket #{ID} updated' => '{APP}: Ticket #{ID} aktualisiert',
    '{USER} ({EMAIL}) have opened a ticket with the following message:' => '{USER} ({EMAIL}) hat ein Ticket mit der folgenden Nachricht geöffnet:',
    '{USER} closed the ticket.' => '{USER} hat das Ticket geschlossen.',
];
